// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   return (
//     <html lang="en">
//         <body className={`${inter.className}`}>
//           <Navbar/>  
//           {children}
//         </body>
//     </html>
//   );
// }
import Navbar from '@/components/Navbar';
import { Inter } from "next/font/google";


interface RootLayoutProps {
  children: React.ReactNode;
}
const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <div className={`flex flex-col min-h-screen min-w-full ${inter.className}`}>
      <Navbar />
      {children}
    </div>
  );
}